
project_id = "uptuetgtjwwotvxuydjn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[[storage.buckets]]
name = "forestalk_audio"
public = true
file_size_limit = "50MiB"
allowed_mime_types = ["audio/webm", "audio/mp3", "audio/mpeg", "audio/wav"]
