// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uptuetgtjwwotvxuydjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwdHVldGd0and3b3R2eHV5ZGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzOTg1OTIsImV4cCI6MjA1OTk3NDU5Mn0.CSQH3c1xKVCYNOyKgOfs4YbcwV6ZS3jRhScdpHuOZbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);